version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

filters_branches_ignore_main: &filters_branches_ignore_main
  filters:
    branches:
      ignore:
        - main

workflows:
  version: 2
  test_and_release:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          trusted-branch: main
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          <<: *filters_branches_ignore_main
